version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "2323:5432"   # 2323 = порт на твоём компьютере, 5432 = порт внутри контейнера
    environment:
      POSTGRES_USER: amigo
      POSTGRES_PASSWORD: "elamigo23"
      POSTGRES_DB: empresa_amiga   # эта база создастся при запуске
    volumes:
      - pg_data:/var/lib/postgresql/data     # хранение данных
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # скрипт для инициализации
    networks:
      - red_postgres

volumes:
  pg_data:
     driver: local
networks:
  red_postgres:
    name: red_postgres   # имя сети, которое создастся
    driver: bridge