# Imagen Oficial de PostgreSQL
FROM postgres:16

# Evitar mensajes interactivos
ENV DEBIAN_FRONTEND=noninteractive

# Puerto interno por defecto de PostgreSQL
EXPOSE 5432

# Comando por defecto
CMD ["postgres"]
